INSERT INTO game_character (name, image_url) VALUES 
('Simon Muran', 'assets/characters/simon-muran.jpg'),
('Teana', 'assets/characters/teana-1.jpg'),
('Jono', 'assets/characters/jono-1.jpg'),
('Villager 1', 'assets/characters/villager-1.jpg'),
('Villager 2', 'assets/characters/villager-2.jpg'),
('Villager 3', 'assets/characters/villager-3.jpg'),
('Seto 1', 'assets/characters/seto-1.jpg'),
('Heishin', 'assets/characters/heishin-1.jpg'),
('Rex Raptor', 'assets/characters/rex-raptor.jpg'),
('Weevil Underwood', 'assets/characters/weevil-underwood.jpg'),
('Mai Valentine', 'assets/characters/mai-valentine.jpg'),
('Bandit Keith', 'assets/characters/bandit-keith.jpg'),
('Shadi', 'assets/characters/shadi.jpg'),
('Yami Bakura', 'assets/characters/yami-bakura.jpg'),
('Maximillion Pegasus', 'assets/characters/maximillion-pegasus.jpg'),
('Isis', 'assets/characters/isis.jpg'),
('Seto Kaiba', 'assets/characters/seto-kaiba.jpg'),
('Mage Soldier', 'assets/characters/mage-soldier.jpg'),
('Jono 2', 'assets/characters/jono-2.jpg'),
('Teana 2', 'assets/characters/teane-2.jpg'),
('Ocean Mage', 'assets/characters/ocean-mage.jpg'),
('High Mage Secmeton', 'assets/characters/high-mage-secmeton.jpg'),
('Forest Mage', 'assets/characters/forest-mage.jpg'),
('High Mage Anubisius', 'assets/characters/high-mage-anubisius.jpg'),
('Mountain Mage', 'assets/characters/mountain-mage.jpg'),
('High Mage Atenza', 'assets/characters/high-mage-atenza.jpg'),
('Desert Mage', 'assets/characters/desert-mage.jpg'),
('High Mage Martis', 'assets/characters/high-mage-martis.jpg'),
('Meadow Mage', 'assets/characters/meadow-mage.jpg'),
('High Mage Kepura', 'assets/characters/high-mage-kepura.jpg'),
('Labyrinth Mage', 'assets/characters/labyrinth-mage.jpg'),
('Seto 2', 'assets/characters/seto-2.jpg'),
('Sebek', 'assets/characters/sebek.jpg'),
('Neku', 'assets/characters/neku.jpg'),
('Heishin 2', 'assets/characters/heishin-2.jpg'),
('Seto 3', 'assets/characters/seto-3.jpg'),
('Dark Nite', 'assets/characters/dark-nite.jpg'),
('Nitemare', 'assets/characters/nite-mare.jpg'),
('Duel Master K', 'assets/characters/duel-master-k.jpg');